# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b666df3abeff5bf87697768d9ef325118d7e4d5753dc29a650e0675d173ce0dfec10c6524dcaca894543d21ff9800546ec3e0474f9a7a5f971ebf0002c76cbf7

test:
  secret_key_base: a5b246d0e5305b772f1563b478eb42c1809eda8760287c007009b9d0a35d86647fec916aafcb26646580c5e804d8f448a3096f02487f2d5ff09d3f7b3007f4bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
